# Note:
# This file was almost 100% generated by AI, prompted to do an inference tester

from transformers import pipeline

# 1. Path to the folder containing config.json, model.safetensors, etc.
MODEL_DIR = "./best_deberta_model"

# Optional: Map numeric outputs (LABEL_0 / LABEL_1) to human-readable names
# Adjust if 0 means "Not AI" and 1 means "AI" in your training mapping
ID2LABEL = {0: "NOT AI", 1: "AI"}

# 2. Load the pipeline directly from your local folder
print("Loading model and tokenizer...")
classifier = pipeline(
    "text-classification",
    model=MODEL_DIR,
    tokenizer=MODEL_DIR,
    device=-1,  # Change to 0 if you want to run on GPU
)

# 3. Quick test on mock sentences
mock_sentences = [
    "We trained a transformer model using gradient descent and chain-of-thought prompting.",
    "Photosynthesis is the process used by plants to convert light energy into chemical energy.",
    "The new API endpoint allows low-latency streaming of generated tokens.",
    "A civil engineer designed the structural suspension bridge over the river.",
]

print("\n--- RUNNING MOCK TESTS ---")
for text in mock_sentences:
    result = classifier(text)[0]
    # Handle both string labels or default LABEL_0/LABEL_1
    raw_label = result["label"]
    if raw_label.startswith("LABEL_"):
        label_idx = int(raw_label.split("_")[1])
        label_name = ID2LABEL.get(label_idx, raw_label)
    else:
        label_name = raw_label

    score = result["score"]
    print(f"Text: '{text}'")
    print(f"  └─ Prediction: {label_name} ({score * 100:.2f}% confidence)\n")

# 4. Interactive loop for user input
print("--- INTERACTIVE MODE ACTIVE ---")
print("Type a sentence and press Enter to classify. Type 'exit' to quit.\n")

while True:
    user_input = input("Enter text > ").strip()

    if user_input.lower() == "exit":
        print("Exiting...")
        break

    if not user_input:
        continue

    result = classifier(user_input)[0]
    raw_label = result["label"]

    if raw_label.startswith("LABEL_"):
        label_idx = int(raw_label.split("_")[1])
        label_name = ID2LABEL.get(label_idx, raw_label)
    else:
        label_name = raw_label

    score = result["score"]
    print(f" -> Label: {label_name} | Confidence: {score * 100:.2f}%\n")
